services:
  stationbyte_frontend_production:
    environment:
      - AUTH_URL_INTERNAL=${AUTH_URL_INTERNAL}
      - AUTH_SECRET=${AUTH_SECRET}
      - PORT=6300
    user: node
    build:
      context: .
      dockerfile: Dockerfile.production
    container_name: stationbyte_frontend_production
    ports:
      - "6300:6300"
    restart: always
